version: "3.9"

services:
  peter-answers:
    container_name: peter-answers
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/elemusbarrios/peter-answers:1.0.1
    ports:
      - "8080:5000"            # host:container
    environment:
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:5000/').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
